### ISSUE TITLE
Self-referential links under "Edges" list on editor interface

### ISSUE THREAD

**Issue by nwyin** [tnguyen21/cope-frontend-mockup#21]
![image](https://user-images.githubusercontent.com/19523341/128565352-d570a2a5-8e4b-496c-8035-d0065a2ba969.png)

Some nodes are not displaying links properly to connected nodes. Rather than a link to the node that it's connected to, the node displays a link to itself. This is a client-side rendering bug!

**Comment by loganpowell** [comment]
resolved by https://github.com/tnguyen21/cope-frontend-mockup/commit/1004ba7568d2a6d7739869416b45ef57693f59ab
