### ISSUE TITLE
Error with deleting nodes

### ISSUE THREAD

**Issue by nwyin** [tnguyen21/cope-frontend-mockup#24]
A breaking error is thrown when attempting to delete a node
![image](https://user-images.githubusercontent.com/19523341/128896965-882eacfd-aa19-4c41-a836-cbea0b3fb5f8.png)

It appears to be a type-issue while attempting to delete all the `AssetPr`s attached to the node. here is the line of code the error points to:
![image](https://user-images.githubusercontent.com/19523341/128897161-a099368a-f059-4203-a649-08976d781b54.png)
_line 144 here_

**Comment by loganpowell** [comment]
should I jump on this?
